spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  r2dbc:
    url: r2dbc:pool:mysql://mysql:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}



logging:
  level:
    p6spy: info
    org.hibernate:
      SQL: info
      type: info


management:
  endpoints:
    web:
      exposure:
        include: "prometheus"






