spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@localhost:27017/dog?authSource=admin

  redis:
    host: localhost
    port: 6379


logging:
  level:
    p6spy: info
    org.hibernate:
      SQL: debug
      type: trace


management:
  endpoints:
    web:
      exposure:
        include: "prometheus"






