spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  webflux:
    multipart:
      max-in-memory-size: 512KB
      max-parts: 3
      max-disk-usage-per-part: 1024KB
      max-headers-size: 5KB


logging:
  level:
    p6spy: info
    org.hibernate:
      SQL: debug
      type: trace
    org.springframework.r2dbc.core: debug


management:
  endpoints:
    web:
      exposure:
        include: "prometheus"






