spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/ssafy
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    p6spy: info

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"


