spring:
  port: 8000

  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:p6spy:mysql://mysql:3306/${MYSQL_DATABASE}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/dog?authSource=admin

  redis:
    host: redis
    port: 6379

logging:
  level:
    p6spy: info
    org.hibernate:
      SQL: info
      type: info

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
