server:
  port: 8000

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:p6spy:mysql://mysql:3306/dog
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: dog
    password: dog

  data:
    mongodb:
      uri: mongodb://dog:dog@mongodb:27017/dog?authSource=admin

  redis:
    host: redis
    port: 6379

logging:
  level:
    p6spy: info
    org.hibernate:
      SQL: info
      type: info

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"

