spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3308/ssafy
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: ssafy
    password: ssafy

  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    p6spy: info

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"


